### PR TITLE
Merging

### PR DESCRIPTION
**Pull request by BTCTaras**

### CODE REVIEW

**Comment by Luca0208** [comment]
Just looked at the files does your server treat Let's Encrypt certificates as secure? Because I know that java doesn't

**Comment by BTCTaras** [comment]
You mean `server.proxy`? There's nothing there yet, it should just show the default BRB page if you tried opening it in a browser

**Comment by Luca0208** [comment]
yeah I see it, but idk if node.js(i think the krist server was written in node.js) trusts Let's Encrypt  certs as secure

**Comment by BTCTaras** [comment]
Oh, https.ceriat.net is a separate server from krist.ceriat.net, and would probably be in PHP

**Pull request merged**
